name: android-armv8-cpu
on:
  push:
    branches: [master]
    paths:
    - '.github/workflows/android-armv8-cpu.yml'
    - 'CMakeLists.txt'
    - 'cmake/**'
    - 'src/*'
    - 'src/layer/*'
    - 'src/layer/arm/**'
  pull_request:
    branches: [master]
    paths:
    - '.github/workflows/android-armv8-cpu.yml'
    - 'CMakeLists.txt'
    - 'cmake/**'
    - 'src/*'
    - 'src/layer/*'
    - 'src/layer/arm/**'
jobs:
  android-aarch64:
    runs-on: ubuntu-latest
    steps:
    - name: cancel-previous-runs
      uses: styfle/cancel-workflow-action@0.9.0
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v2
    - name: build
      run: |
        mkdir build && cd build
        cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_HOME/ndk-bundle/build/cmake/android.toolchain.cmake -DANDROID_ABI="arm64-v8a" -DANDROID_PLATFORM=android-21 ..
        cmake --build . -j 2
    - name: build-shared
      run: |
        mkdir build-shared && cd build-shared
        cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_HOME/ndk-bundle/build/cmake/android.toolchain.cmake -DANDROID_ABI="arm64-v8a" -DANDROID_PLATFORM=android-21 -DNCNN_SHARED_LIB=ON -DNCNN_ENABLE_LTO=ON ..
        cmake --build . -j 2
