name: ios-simulator
on: [push, pull_request]
jobs:
  ios-iphone-simulator:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/ios.toolchain.cmake -DIOS_PLATFORM=SIMULATOR ..
    - name: build
      run: cmake --build build -j 2

  ios-iphone-simulator-nostdio-nostring:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/ios.toolchain.cmake -DIOS_PLATFORM=SIMULATOR -DNCNN_STDIO=OFF -DNCNN_STRING=OFF -DNCNN_BUILD_TESTS=OFF -DNCNN_BUILD_BENCHMARK=OFF ..
    - name: build
      run: cmake --build build -j 2
