name: ios-cpu
on: [push, pull_request]
jobs:
  ios-iphone-os:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/ios.toolchain.cmake -DIOS_PLATFORM=OS -DNCNN_SIMPLEOMP=ON ..
    - name: build
      run: cmake --build build -j 2
