name: linux-x64-cpu-gcc
on: [push, pull_request]
jobs:
  linux-gcc:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: update
      run: sudo apt-get update
    - name: protobuf
      run: sudo apt-get install libprotobuf-dev protobuf-compiler libopencv-dev
    - name: configure
      run: mkdir build && cd build && cmake -DNCNN_BUILD_TESTS=ON ..
    - name: build
      run: cmake --build build -j 2
    - name: test
      run: cd build && ctest --output-on-failure -j 2

  linux-gcc-avx2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: update
      run: sudo apt-get update
    - name: protobuf
      run: sudo apt-get install libprotobuf-dev protobuf-compiler libopencv-dev
    - name: configure
      run: mkdir build && cd build && cmake -DNCNN_AVX2=ON -DNCNN_BUILD_TESTS=ON ..
    - name: build
      run: cmake --build build -j 2
    - name: test
      run: cd build && ctest --output-on-failure -j 2

  linux-gcc-cpp03:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/host.gcc-c++03.toolchain.cmake -DNCNN_BUILD_TESTS=ON -DNCNN_BUILD_TOOLS=OFF -DNCNN_BUILD_EXAMPLES=OFF ..
    - name: build
      run: cmake --build build -j 2
    - name: test
      run: cd build && ctest --output-on-failure -j 2

  linux-gcc-nostdio-nostring:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: mkdir build && cd build && cmake -DNCNN_STDIO=OFF -DNCNN_STRING=OFF -DNCNN_BUILD_TESTS=OFF -DNCNN_BUILD_BENCHMARK=OFF -DNCNN_BUILD_TOOLS=OFF -DNCNN_BUILD_EXAMPLES=OFF ..
    - name: build
      run: cmake --build build -j 2

  linux-gcc-simplestl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/host-c.gcc.toolchain.cmake -DNCNN_STDIO=ON -DNCNN_STRING=ON -DNCNN_SIMPLESTL=ON -DNCNN_BUILD_TESTS=ON -DNCNN_BUILD_BENCHMARK=OFF -DNCNN_BUILD_TOOLS=OFF -DNCNN_BUILD_EXAMPLES=OFF ..
    - name: build
      run: cmake --build build -j 2
    - name: test
      run: cd build && ctest --output-on-failure -j 2
