name: macos-x64-cpu
on: [push, pull_request]
jobs:
  macos-clang:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: protobuf
      run: brew install protobuf opencv3
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: build
      run: cmake --build build -j 2
    - name: test
      run: cd build && ctest --output-on-failure -j 2

  macos-clang-nostdio-nostring:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: mkdir build && cd build && cmake -DNCNN_STDIO=OFF -DNCNN_STRING=OFF -DNCNN_BUILD_TESTS=OFF -DNCNN_BUILD_BENCHMARK=OFF -DNCNN_BUILD_TOOLS=OFF -DNCNN_BUILD_EXAMPLES=OFF ..
    - name: build
      run: cmake --build build -j 2
